/**
 * SimpLESS Browser Push
 * =====================
 * This script causes CSS files generated by SimpLESS to reload.
 *
 * @author: Christian Engel <hello@wearekiss.com>
 * @version: 1
 */
(function (){
    'use strict';

    var i,
        s,
        url,
        ioUrl;

    url = 'http://%host%/socket.io/socket.io.js';
    ioUrl = 'http://%host%';

    function ioLoaded(){
        var socket = io.connect(ioUrl),
            sheets;

        sheets = document.getElementsByTagName('link');

        for (i = 0; i < document.styleSheets.length; i++) {
            if(document.styleSheets[i].href){
                (function (sheet){
                    var i,
                        originalURL,
                        appender,
                        domElm;

                    for (i = 0; i < sheets.length; i++) {
                        if(sheets[i].href === sheet.href){
                            domElm = sheets[i];
                            break;
                        }
                    }

                    if(domElm === undefined){
                        return;
                    }

                    originalURL = domElm.href;

                    appender = originalURL.search(/\?/) > -1 ? '&' : '?';

                    socket.on(sheet.href.split('/').pop(), function (){
                        console.log('SimpLESS: reloading ' + originalURL);
                        domElm.href = originalURL + appender + Math.random().toString().split('.').pop();
                    });
                })(document.styleSheets[i]);
            }
        }
    }

    if(window.io && typeof window.io.connect === 'function'){
        ioLoaded();
        return;
    }

    s = document.createElement('script');

    s.onload = ioLoaded;

    s.src = url;

    document.head.appendChild(s);
})();